[Rule]
# DOMAIN,raw.githubusercontent.com,PROXY
# RULE-SET,https://raw.githubusercontent.com/billypon/gfwlist/refs/heads/master/gfwlistx-clash.txt,PROXY
DOMAIN,cdn.jsdelivr.net,PROXY
RULE-SET,https://cdn.jsdelivr.net/gh/billypon/gfwlist@master/gfwlistx-clash.txt,PROXY
FINAL,DIRECT
